### ISSUE TITLE
Not 64-bit on Win?

### ISSUE THREAD

**Issue by nilskp** [fasto/fastoredis#44]
Just downloaded "64 bit Windows 0.5.6 Installer", but it wants to install into "Program Files (x86)", which tells me it's either not 64-bit or is somehow picking the wrong folder.

**Comment by topilski** [comment]
Hello, no now we support only 64 bit version, i think it is cpack issue. Please check workflow FastoRedis on your machine.

**Comment by topilski** [comment]
Fixed in rev #b4acae08486368964cdd95c69e9554943d2f85b3

**Comment by topilski** [comment]
Hello @nilskp, we published new release of FastoRedis, please check it if everything works correctly close please your issue, thanks. If you will find something else tell us.

**Comment by nilskp** [comment]
@topilski 
I tried `fastoredis-0.6.0-x86_64.exe` and it appears to pick `Program Files` now. I didn't install it however.

Instead I also downloaded `fastoredis-0.6.0-x86_64.zip`, but that appears to have no executable.

**Comment by topilski** [comment]
@nilskp  please check this issue, and close if fixed.
