### ISSUE TITLE
Don't use `KEYS *`, switch to `SCAN *` if possible

### ISSUE THREAD

**Issue by badboy** [fasto/fastoredis#49]
I just wanted to try fastoredis, but it already fails with a small instance (~20Mb of data).
The main window is completely unresponsive.

This is probably largely due to the use of `KEYS *` (https://github.com/fasto/fastoredis//blob/master/src/core/redis/redis_driver.cpp#L39), which is one of the most expensive commands in Redis. It's blocking and _always_ needs to scan the whole database.
An alternative is to use the [SCAN](http://redis.io/commands/scan) command, that will iteratively scan the whole database without blocking for too long (the downside being that you might miss keys if they are added in between).

For now I advise atleast having a small warning that this should best not be used against large production instances.
In the longer run replacing `KEYS *` is definitely the desired solution.

**Comment by topilski** [comment]
Hello @badboy, thank you for issue, i didn't test FastoRedis on big database, so how can i understand i must execute 'scan' command in a loop while server not return 0. And the main question is how present this functionaliti to users, now it is simply load content. @badboy, how do you think we can make more options where user may choose how much keys he wants and what patterns for selection to use?

**Comment by topilski** [comment]
@badboy in 0.7.0 version you can try new behavior, wait your opinion.

**Comment by badboy** [comment]
Seems to work much better now.
