### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by nilskp** [fasto/fastoredis#51]
I just tried 0.6.2 and I cannot see any data. I'm using the zip Win x64 version.

![image](https://cloud.githubusercontent.com/assets/74843/6333825/da24df02-bb55-11e4-940e-eb0669a7a5c6.png)

**Comment by topilski** [comment]
Hello @nilskp, please execute "Set default", and after that "Load content of database".

**Comment by nilskp** [comment]
Ok, that brought me a step further. But now if I try to view values, I get WRONGTYPE.

Generally, I feel like there's way too much right-clicking needed to make this GUI fluid. E.g. even clicking a key does nothing. I still have to right-click then select "Value". It should be possible to do the most basic stuff by just clicking through.

**Comment by topilski** [comment]
@nilskp what you mean WRONGTYPE? If not hard for you please make screanshoot for this bug. Your solution very interesting, it will be implemented in next releases.

**Comment by nilskp** [comment]
@topilski 

![image](https://cloud.githubusercontent.com/assets/74843/6336322/64dbd0cc-bb67-11e4-98ee-517efbcde218.png)

**Comment by nilskp** [comment]
Or this view:

![image](https://cloud.githubusercontent.com/assets/74843/6336638/9520c2fe-bb69-11e4-87a5-512d1fff05f3.png)

**Comment by topilski** [comment]
Hello @nilskp, we released 0.7.0 version please try to reproduce this bug again.
